name: Publish development version of docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
      - name: Configure Git Credentials
        run: |
          git config user.name ci-deployment[bot]
          git config user.email ci-deployment@noreply
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # 5.1.0
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # 4.0.2
        with:
          key: docs-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            docs-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force